version: "3.9"


services:
  nginx:
    image: nginx
    container_name: rental_web_server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - rentals_network
    
  db:
    image: postgres:12-alpine
    container_name: rental_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - rentals_network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rental_app
    volumes:
      - .:/app
      - ./scripts/run.sh:/app/run.sh
    entrypoint: sh -c "./scripts/run.sh"
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - rentals_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

networks:
  rentals_network: