# Generated by Django 5.0.3 on 2024-03-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='cover_i',
        ),
    ]
