# Generated by Django 5.0.3 on 2024-03-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rename_isbn_book_cover_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(),
        ),
    ]
